### ISSUE TITLE
Missing additions and map setting in params

### ISSUE THREAD

**Issue by LangMarcus** [ohmcodes/WindowsGSM.Soulmask#2]
You missed to pass the additions property and the map settings to parameters. I also changed the naming of the property to better reflect the meaning of the data within the property.

I renamed the Additions property to RequiredParams:
        public string RequiredParams = "-UTF8Output -forcepassthrough -server %* -log -EchoPort=18888";

Params part could be changed to:
            string param = $" {_serverData.ServerMap}";
            param += $" {RequiredParams}";
            param += $" -MULTIHOME={_serverData.ServerIP}";
            param += $" -SteamServerName={WrapInQuotes(_serverData.ServerName)}";
            param += $" -MaxPlayers={_serverData.ServerMaxPlayer}";
            param += $" -Port={_serverData.ServerPort}";
            param += $" -QueryPort={_serverData.ServerQueryPort}";
            param += $" {_serverData.ServerParam}";

**Comment by ohmcodes** [comment]
theres no map on params check here https://soulmask.fandom.com/wiki/Private_Server

**Comment by LangMarcus** [comment]
Yeah but the map is a nameless parameter that needs to be submitted. With your Version 1.0 i never got the server to run because of the missing map information

**Comment by ohmcodes** [comment]
download latest
