### ISSUE TITLE
Shutdown

### ISSUE THREAD

**Issue by Dylfin** [ohmcodes/WindowsGSM.Soulmask#3]
I'm not sure, but the current shutdown looks like it's not right.
According to https://soulmask.fandom.com/wiki/Private_Server#Shutting_down_the_server_(taking_Windows_as_an_example)
it should be done via command to avoid rollback

**Comment by ohmcodes** [comment]
> I'm not sure, but the current shutdown looks like it's not right. According to https://soulmask.fandom.com/wiki/Private_Server#Shutting_down_the_server_(taking_Windows_as_an_example) it should be done via command to avoid rollback

WGSM doesnt have telnet or even rcon i have an article that you can send a command via console but at the moment i cant find it so i can try

**Comment by ohmcodes** [comment]
> I'm not sure, but the current shutdown looks like it's not right. According to https://soulmask.fandom.com/wiki/Private_Server#Shutting_down_the_server_(taking_Windows_as_an_example) it should be done via command to avoid rollback

I FOUND IT! you could try this script replace the shutdown function
```
Functions.ServerConsole.SendWaitToMainWindow("quit 180");
```

**Comment by Dylfin** [comment]
Nope, not working, main window isn't enough.
But it's probably possible to do via telnet, C# isn't my specialty, but I will try if I find a time.

**Comment by ohmcodes** [comment]
> Nope, not working, main window isn't enough. But it's probably possible to do via telnet, C# isn't my specialty, but I will try if I find a time.

I will push an update for this matter
