### ISSUE TITLE
Caution, this gsm would cause an inconsistent save file on server

### ISSUE THREAD

**Issue by kimklai** [ohmcodes/WindowsGSM.Soulmask#5]
Hope you can fix this issue...

But right now, the latest source code commited on 6/17/2024 is not safe.
Use this script to trigger soulmask restart by windowsgsm would cause server data inconsistent.

- Symptom: just died and revive 5 minutes ago, before server restarted. After server restarted, the equipment and items on characters will be old data, but the map location is new.
- Guess: I think maybe caused by the ^c in the script.

**Comment by ohmcodes** [comment]
have you tried the latest version? ^c script is just to close the terminal like forcefully shutdown
