### ISSUE TITLE
Unable to Update

### ISSUE THREAD

**Issue by Th4nat0s1s** [ohmcodes/WindowsGSM.Soulmask#6]
Not sure if this is a GSM issue or a Plugin issue, but I was unable to update the server from 0.1.4 to 0.1.5 earlier today. I eventually had to update the game outside of GSM and then copy the files over to apply the update.

**Comment by darkt1981** [comment]
no issues here must be your gsm

**Comment by Th4nat0s1s** [comment]
Ill test again when a new update drops I guess and report back.
